version: '3.3'
services:
  updater:
    image: 'ed-updater:latest'
    volumes:
      - 'dbdata:/usr/src/app/data'
    build: ./updater
    environment:
      - DB_PATH=sqlite:///data/updater.db


  server:
    image: 'ed-server:latest'
    volumes:
      - 'dbdata:/usr/src/app/data'
    build: ./server
    environment:
      - DB_PATH=sqlite:///data/updater.db
    networks:
      - edmm


  web:
    image: nginx
    volumes:
      - ./client/dist:/var/www/html:ro
      - ./templates:/etc/nginx/templates
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=_
    networks:
      - edmm

volumes:
  dbdata:

networks:
  edmm: