version: '3.3'
services:
  updater:
    image: 'ed-updater:latest'
    volumes:
      - './updater:/usr/src/app'
      # - 'dbdata:/usr/src/app/data'
    build: ./updater
    environment:
      - DB_PATH=mysql+pymysql://root:5j2R03lurJHs@db/edmm
    networks:
      - edmm
    depends_on:
      - "db"

  server:
    image: 'ed-server:latest'
    volumes:
      - './server:/usr/src/app'
      # - 'dbdata:/usr/src/app/data'
    build: ./server
    environment:
      - DB_PATH=mysql+pymysql://root:5j2R03lurJHs@db/edmm
    networks:
      - edmm
    ports:
      - "4000:4000"
    depends_on:
      - "db"

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: '5j2R03lurJHs'
      MARIADB_DATABASE: edmm
    networks:
      - edmm
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

networks:
  edmm: